apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-insurance-deployment
spec:
  replicas: 2 # Run 2 copies of the app for high availability
  selector:
    matchLabels:
      app: vehicle-insurance
  template:
    metadata:
      labels:
        app: vehicle-insurance
    spec:
      containers:
      - name: vehicle-insurance-app
        # The image will be updated by the CI/CD pipeline
        image: 427976559274.dkr.ecr.us-east-1.amazonaws.com/vehicleproj:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: mongodb-secret # Reference the K8s secret
              key: MONGODB_URL