apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-insurance-deployment
spec:
  replicas: 2 # Run 2 copies of the app for high availability
  selector:
    matchLabels:
      app: vehicle-insurance
  template:
    metadata:
      labels:
        app: vehicle-insurance
    spec:
      serviceAccountName: vehicle-insurance-service-account
      containers:
      - name: vehicle-insurance-app
        image: 340545199393.dkr.ecr.us-east-1.amazonaws.com/vehicle-insurance-repo:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: mongodb-secret # Reference the K8s secret
              key: MONGODB_URL
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret # Reference the K8s secret for AWS
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret # Reference the K8s secret for AWS
              key: AWS_SECRET_ACCESS_KEY